version: '2'
services:
    washcar-app:
        image: washcar
        external_links:
            - washcar-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/washcar?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    washcar-mysql:
        extends:
            file: mysql.yml
            service: washcar-mysql
