version: '2'
services:
    angular4-app:
        image: angular4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://angular4-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Angular4
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angular4-mongodb:
        extends:
            file: mongodb.yml
            service: angular4-mongodb
