version: '2'
services:
    burndown-app:
        image: burndown
        external_links:
            - burndown-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Burndown
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    burndown-mongodb:
        extends:
            file: mongodb.yml
            service: burndown-mongodb
