version: '2'
services:
    burndown-mongodb:
        container_name: burndown-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/Burndown/mongodb/:/data/db/
